export const everything = {
  rules: {
    "affirmation-closers": true,
    "avg-sentence-length": true,
    "colon-dramatic": true,
    "coleman-liau": true,
    "demonstrative-emphasis": true,
    "em-dashes": true,
    "exclamation-density": true,
    "fake-timestamps": true,
    "false-question": true,
    "flesch-kincaid": true,
    "fragment-stacking": true,
    "gunning-fog": true,
    "hedge-stacking": true,
    "humble-bragger": true,
    "jargon-faker": true,
    "llm-openers": true,
    "negation-reframe": true,
    "paragraph-length": true,
    "prohibited-phrases": true,
    "prohibited-words": true,
    "recommended-terms": true,
    "required-terms": true,
    "sentence-case": true,
    simplicity: true,
    "smart-quotes": true,
    "summative-closer": true,
    "triple-repeat": true,
    "word-repetition": true
  }
};
