name: Dist

on:
  workflow_call:
    inputs:
      tag:
        description: Git tag to package and publish.
        required: true
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: Git tag to package and publish.
        required: true
        type: string

permissions:
  contents: write

jobs:
  plan:
    runs-on: ubuntu-22.04
    outputs:
      manifest: ${{ steps.plan.outputs.manifest }}
      tag_flag: ${{ steps.plan.outputs.tag_flag }}
    env:
      GH_TOKEN: ${{ github.token }}
    defaults:
      run:
        working-directory: apps/prosesmasher
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
          submodules: recursive

      - name: Install dist
        shell: bash
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/axodotdev/cargo-dist/releases/download/v0.31.0/cargo-dist-installer.sh | sh

      - name: Cache dist
        uses: actions/upload-artifact@v6
        with:
          name: cargo-dist-cache
          path: ~/.cargo/bin/dist

      - name: Plan release artifacts
        id: plan
        run: |
          dist host --steps=create --tag="${{ inputs.tag }}" --output-format=json > plan-dist-manifest.json
          echo "manifest=$(jq -c "." plan-dist-manifest.json)" >> "$GITHUB_OUTPUT"
          echo "tag_flag=--tag=${{ inputs.tag }}" >> "$GITHUB_OUTPUT"

      - name: Upload dist plan
        uses: actions/upload-artifact@v6
        with:
          name: artifacts-plan-dist-manifest
          path: apps/prosesmasher/plan-dist-manifest.json

  build-local-artifacts:
    name: build-local-artifacts (${{ join(matrix.targets, ', ') }})
    needs: plan
    if: ${{ fromJson(needs.plan.outputs.manifest).ci.github.artifacts_matrix.include != null }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.plan.outputs.manifest).ci.github.artifacts_matrix }}
    runs-on: ${{ matrix.runner }}
    container: ${{ matrix.container && matrix.container.image || null }}
    env:
      GH_TOKEN: ${{ github.token }}
      BUILD_MANIFEST_NAME: target/distrib/${{ join(matrix.targets, '-') }}-dist-manifest.json
    defaults:
      run:
        working-directory: apps/prosesmasher
    steps:
      - name: Enable Windows long paths
        run: git config --global core.longpaths true

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
          submodules: recursive

      - name: Install Rust non-interactively if not already installed
        if: ${{ matrix.container }}
        run: |
          if ! command -v cargo > /dev/null 2>&1; then
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          fi

      - name: Install dist
        run: ${{ matrix.install_dist.run }}

      - name: Fetch local artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: artifacts-*
          path: apps/prosesmasher/target/distrib/
          merge-multiple: true

      - name: Install dependencies
        run: ${{ matrix.packages_install }}

      - name: Build artifacts
        run: dist build ${{ needs.plan.outputs.tag_flag }} --print=linkage --output-format=json ${{ matrix.dist_args }} > dist-manifest.json

      - id: cargo-dist
        name: Post-build
        shell: bash
        run: |
          cp dist-manifest.json "$BUILD_MANIFEST_NAME"
          echo "paths<<EOF" >> "$GITHUB_OUTPUT"
          dist print-upload-files-from-manifest --manifest dist-manifest.json | sed 's#^#apps/prosesmasher/#' >> "$GITHUB_OUTPUT"
          echo "apps/prosesmasher/$BUILD_MANIFEST_NAME" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: artifacts-build-local-${{ join(matrix.targets, '_') }}
          path: ${{ steps.cargo-dist.outputs.paths }}

  build-global-artifacts:
    needs:
      - plan
      - build-local-artifacts
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ github.token }}
      BUILD_MANIFEST_NAME: target/distrib/global-dist-manifest.json
    defaults:
      run:
        working-directory: apps/prosesmasher
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
          submodules: recursive

      - name: Install cached dist
        uses: actions/download-artifact@v7
        with:
          name: cargo-dist-cache
          path: ~/.cargo/bin/

      - name: Make dist executable
        run: chmod +x ~/.cargo/bin/dist

      - name: Fetch local artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: artifacts-*
          path: apps/prosesmasher/target/distrib/
          merge-multiple: true

      - id: cargo-dist
        shell: bash
        run: |
          dist build ${{ needs.plan.outputs.tag_flag }} --output-format=json "--artifacts=global" > dist-manifest.json
          cp dist-manifest.json "$BUILD_MANIFEST_NAME"

          echo "paths<<EOF" >> "$GITHUB_OUTPUT"
          jq --raw-output ".upload_files[]" dist-manifest.json | sed 's#^#apps/prosesmasher/#' >> "$GITHUB_OUTPUT"
          echo "apps/prosesmasher/$BUILD_MANIFEST_NAME" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: artifacts-build-global
          path: ${{ steps.cargo-dist.outputs.paths }}

  host:
    needs:
      - plan
      - build-local-artifacts
      - build-global-artifacts
    if: ${{ always() && needs.plan.result == 'success' && (needs.build-global-artifacts.result == 'skipped' || needs.build-global-artifacts.result == 'success') && (needs.build-local-artifacts.result == 'skipped' || needs.build-local-artifacts.result == 'success') }}
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: apps/prosesmasher
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
          submodules: recursive

      - name: Install cached dist
        uses: actions/download-artifact@v7
        with:
          name: cargo-dist-cache
          path: ~/.cargo/bin/

      - name: Make dist executable
        run: chmod +x ~/.cargo/bin/dist

      - name: Fetch artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: artifacts-*
          path: apps/prosesmasher/target/distrib/
          merge-multiple: true

      - id: host
        shell: bash
        run: |
          dist host ${{ needs.plan.outputs.tag_flag }} --steps=upload --steps=release --output-format=json > dist-manifest.json
          echo "manifest=$(jq -c "." dist-manifest.json)" >> "$GITHUB_OUTPUT"

      - name: Upload dist manifest
        uses: actions/upload-artifact@v6
        with:
          name: artifacts-dist-manifest
          path: apps/prosesmasher/dist-manifest.json

      - name: Download GitHub artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: artifacts-*
          path: artifacts
          merge-multiple: true

      - name: Cleanup
        run: rm -f ../../artifacts/*-dist-manifest.json

      - name: Create GitHub release
        env:
          PRERELEASE_FLAG: ${{ fromJson(steps.host.outputs.manifest).announcement_is_prerelease && '--prerelease' || '' }}
          ANNOUNCEMENT_TITLE: ${{ fromJson(steps.host.outputs.manifest).announcement_title }}
          ANNOUNCEMENT_BODY: ${{ fromJson(steps.host.outputs.manifest).announcement_github_body }}
          RELEASE_COMMIT: ${{ github.sha }}
        run: |
          echo "$ANNOUNCEMENT_BODY" > "$RUNNER_TEMP/notes.txt"
          if gh release view "${{ inputs.tag }}" >/dev/null 2>&1; then
            gh release upload "${{ inputs.tag }}" ../../artifacts/* --clobber
            gh release edit "${{ inputs.tag }}" $PRERELEASE_FLAG --title "$ANNOUNCEMENT_TITLE" --notes-file "$RUNNER_TEMP/notes.txt"
          else
            gh release create "${{ inputs.tag }}" --target "$RELEASE_COMMIT" $PRERELEASE_FLAG --title "$ANNOUNCEMENT_TITLE" --notes-file "$RUNNER_TEMP/notes.txt" ../../artifacts/*
          fi
