name: Release

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - production

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/prosesmasher
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-semver-checks
        run: cargo install cargo-semver-checks

      - name: Release-plz release-pr
        uses: release-plz/action@v0.5
        with:
          command: release-pr
          config: apps/prosesmasher/release-plz.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release-plz release
        uses: release-plz/action@v0.5
        with:
          command: release
          config: apps/prosesmasher/release-plz.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
