name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  dist:
    name: Dist
    uses: ./.github/workflows/dist.yml
    with:
      tag: ${{ github.ref_name }}
    secrets: inherit
